softeer5th/Team5-EQUUS-N

docs/사용자 프로필 관리/사용자 프로필 관리 SD.drawio

FD-162
- 사용자 프로필 관리 기능의 Use Case 분석
- 시퀀스 다이어그램 추가

[FD-162] docs: 사용자 프로필 관리 기능 유즈케이스 시퀀스 다이어그램 추가

---

front-end/src/App2.jsx
front-end/src/components/Tag.jsx

- 태그 컴포넌트 작성
- enum역할을 하는 TagType 불변객체 사용해야함
- 문자열을 children으로 전달
- "팀장"과 "내 역할"은 정적문자열이므로 TagType의 value로 지정하여 활용

[FD-192]  common components 1

---

front-end/package-lock.json
front-end/package.json
front-end/src/App3.jsx
front-end/src/components/buttons/FeedBackButton.jsx
front-end/src/components/buttons/LargeButton.jsx
front-end/src/components/buttons/MediumButton.jsx
front-end/src/components/buttons/SmallButton.jsx
front-end/src/main.jsx

- 기본 버튼 컴포넌트를 만들었습니다
- 라지 / 미디움 / 스몰 버튼 세 종류
- 사이즈별 버튼들은 또 다시 활성화/비활성화 + 테두리있음/없음 으로 나뉘어짐
- 텍스트 아무것도 입력 안하면 + 기호 있는 추가 버튼 나옴
- 피드백 버튼 컴포넌트 만들었습니다
- isGoodClicked 와 isBadClicked 상태 가지며, 둘 중 하나만 눌러지도록 함

Fd 188 버튼 컴포넌트 개발

---

docs/팀 관리/팀 관리 SD.drawio

FD-163
- 팀 관리 기능의 Use Case 분석
- 시퀀스 다이어그램 추가

[FD-163] docs: 팀 관리 유즈케이스 시퀀스 다이어그램 추가

---

back-end/.gitignore
back-end/build.gradle
back-end/src/main/resources/application-dev.yml
back-end/src/main/resources/application.properties
back-end/src/main/resources/application.yml

FD-219
- 개발과 운영 환경의 application.yml 파일을 분리
- 공통: application.yml
- 개발: application-dev.yml
- 운영: application-prod.yml
-  기본 프로파일을 dev로 변경
※ spring.profiles.active 값에 따라 개발(dev), 운영(prod) 를 구분합니다.

Fd 219 개발 운영 환경별 설정파일 분리

---

docs/일정 관리/일정 관리 SD.drawio

FD-164
- 일정 관리 기능의 Use Case 분석
- 시퀀스 다이어그램 추가

[FD-164] docs: 일정 관리 유즈케이스 시퀀스 다이어그램 추가

---

back-end/build.gradle
back-end/src/main/resources/application.yml

FD-220
- Swagger 어노테이션을 기반으로 문서를 생성해주는 springdoc 라이브러리 의존성 추가
- Swagger 관련 기본 설정 추가

[FD-220] build: swagger 의존성 및 기본 설정추가

---

front-end/src/App2.jsx
front-end/src/assets/Icons/plus_m.svg
front-end/src/components/Icon.jsx
front-end/src/components/Tag.jsx
front-end/src/components/buttons/AiButton.jsx
front-end/src/components/buttons/KeywordButton.jsx
front-end/src/components/buttons/TextButton.jsx
front-end/src/index.css
front-end/src/main.jsx

- AI, 텍스트, 키워드 버튼 컴포넌트들 만들었습니다
- Icon 컴포넌트에서 className 부분 뒤로 보냈습니다
- **index.css 수정했습니다**
- 커서 올리면 손 나타나게 했씁니다
- 버튼 클릭 피드백을 받기 위해서 임시로 클릭시에 크기 줄어들게 했습니다

[FD-192] AI, 텍스트, 키워드 버튼, 태그 컴포넌트 개발

---

back-end/build.gradle
back-end/src/main/java/com/feedhanjum/back_end/domain/Feedback.java
back-end/src/main/java/com/feedhanjum/back_end/domain/FeedbackType.java
back-end/src/main/java/com/feedhanjum/back_end/domain/FrequentFeedbackRequest.java
back-end/src/main/java/com/feedhanjum/back_end/domain/Member.java
back-end/src/main/java/com/feedhanjum/back_end/domain/RegularFeedbackRequest.java
back-end/src/main/java/com/feedhanjum/back_end/domain/Retrospect.java
back-end/src/main/java/com/feedhanjum/back_end/domain/Schedule.java
back-end/src/main/java/com/feedhanjum/back_end/domain/ScheduleMember.java
back-end/src/main/java/com/feedhanjum/back_end/domain/ScheduleRole.java
back-end/src/main/java/com/feedhanjum/back_end/domain/Team.java
back-end/src/main/java/com/feedhanjum/back_end/domain/TeamMember.java
back-end/src/main/java/com/feedhanjum/back_end/domain/TeamRole.java
back-end/src/main/java/com/feedhanjum/back_end/domain/Todo.java
docs/도메인 모델.drawio

늦어져서 죄송합니다... 다음부턴 일 생기면 바로바로 말씀드리고 도움 요청할게요
FD-221
- 중복된 필드 (연관관계로 표현되는 필드) 제거
- Member
- Team
- Schedule
- TeamMember
- ScheduleMember
- FrequentFeedbackRequest
- RegularFeedbackRequest
- Todo
- Feedback
- Retrospect
- AggregateRoot 인터페이스 생성 및 구현?

[FD-221] feat: 핵심 도메인 구현

---

back-end/src/main/java/com/feedhanjum/back_end/domain/Feedback.java
back-end/src/main/java/com/feedhanjum/back_end/domain/FrequentFeedbackRequest.java
back-end/src/main/java/com/feedhanjum/back_end/domain/Member.java
back-end/src/main/java/com/feedhanjum/back_end/domain/RegularFeedbackRequest.java
back-end/src/main/java/com/feedhanjum/back_end/domain/ScheduleMember.java
back-end/src/main/java/com/feedhanjum/back_end/domain/Team.java
back-end/src/main/java/com/feedhanjum/back_end/domain/TeamMember.java
back-end/src/main/java/com/feedhanjum/back_end/domain/TeamRole.java
back-end/src/main/java/com/feedhanjum/back_end/domain/Todo.java
docs/도메인 모델.drawio

FD-221
- 사용하지 않는 필드 제거
- 변경되지 않을 필드의 setter 접근제어자 private로 변경
- 도메인의 필드에 존재하는 리스트 초기화

[FD-221] fix: 사용하지 않는 코드 제거, 접근 제어자 수정, 버그 수정

---

back-end/src/main/java/com/feedhanjum/back_end/domain/ScheduleRole.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Feedback.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/FeedbackType.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/FrequentFeedbackRequest.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/RegularFeedbackRequest.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Retrospect.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/RetrospectRepository.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/service/RetrospectService.java
back-end/src/main/java/com/feedhanjum/back_end/member/domain/Member.java
back-end/src/main/java/com/feedhanjum/back_end/member/repository/MemberRepository.java
back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/Schedule.java
back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/ScheduleMember.java
back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/ScheduleRole.java
back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/Todo.java
back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
back-end/src/main/java/com/feedhanjum/back_end/team/domain/TeamMember.java
back-end/src/main/java/com/feedhanjum/back_end/team/domain/TeamRole.java
back-end/src/main/java/com/feedhanjum/back_end/team/repository/TeamRepository.java
back-end/src/test/java/com/feedhanjum/back_end/feedback/service/RetrospectServiceTest.java

FD-100
- Repository 추가: MemberRepository, TeamRepository, RetrospectRepository
- Service 추가: RetrospectService
- 회고 작성 구현: RetrospectService.writeRetrospect()
- 회고 작성 테스트 구현: RetrospectServiceTest

[FD-100] feat: 회고 작성하기

---

back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/RegularFeedbackRequest.java
back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/ScheduleMember.java
back-end/src/main/java/com/feedhanjum/back_end/team/domain/FrequentFeedbackRequest.java
back-end/src/main/java/com/feedhanjum/back_end/team/domain/TeamMember.java

[FD-226] refactor: 도메인 별 패키지 분리

---

front-end/src/components/FeedBack.jsx
front-end/src/components/ProfileImage.jsx

피드백 컴포넌트 완료했습니다
- FeedBackType 이라는 불변객체 생성하여 type(보낸 피드백, 받은 피드백, 회고) 에 따라 내용 달라지도록 구성함
https://drive.google.com/file/d/1LpZQPDmsVNI9IPgJkkIlvWTpEfzKg2Tx/view?usp=drive_link

[FD-193] 피드백 컴포넌트 개발

---

front-end/src/components/Alarm.jsx
front-end/src/components/Calendar.jsx
front-end/src/components/CalendarParts.jsx
front-end/src/components/FeedBack.jsx
front-end/src/components/MainCard2.jsx
front-end/src/components/MemberElement.jsx
front-end/src/components/NavBar2.jsx
front-end/src/components/ProfileImage.jsx
front-end/src/components/ScheduleCard.jsx
front-end/src/components/TeamElement.jsx
front-end/src/components/Toast.jsx
front-end/src/components/buttons/FeedBackButton.jsx
front-end/src/components/buttons/LargeButton.jsx
front-end/src/components/buttons/MediumButton.jsx
front-end/src/components/buttons/SmallButton.jsx
front-end/src/utility/time.js

[FD-187] 공통 컴포넌트 개발

---

back-end/src/test/java/com/feedhanjum/back_end/auth/infra/AuthInterceptorTest.java

FD-237
AuthInterceptor 가 response.getWriter() 를 통해 writer 를 획득하고 사용하려다가 NPE가 발생하는 문제 수정

[FD-237] fix: AuthInterceptor 버그 수정

---

back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java

FD-36
FD-247
- 수시 피드백 요청 시 팀 이름을 받던 것을 팀 id를 받도록 변경

[FD-247] 수시 피드백 요청 인자를 팀 이름에서 팀 id로 변경

---

back-end/src/main/java/com/feedhanjum/back_end/feedback/service/RetrospectService.java
back-end/src/test/java/com/feedhanjum/back_end/feedback/service/RetrospectServiceTest.java

FD-101
FD-245
- 회고 조회 시 인자를 팀 이름에서 팀 id로 변경

[FD-245] 회고 조회 인자 팀 id로 변경

---

back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Feedback.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/FeedbackCategory.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/FeedbackFeeling.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/ObjectiveFeedback.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java

FD-37
FD-242
- 기존 FeedbackCategory -> FeedbackFeeling 이름 변경
- 객관식 피드백의 계층적인 분류 구조 구성
- FeedbackFeeling -> FeedbackCategory -> ObjectiveFeedback

[FD-242] 객관식 피드백 재구성

---

back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Feedback.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/event/FeedbackLikedEvent.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
back-end/src/main/java/com/feedhanjum/back_end/member/domain/Member.java
back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java

[FD-105] 피드백 좋아요/취소

---

back-end/src/main/java/com/feedhanjum/back_end/auth/controller/AuthController.java
back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/MemberSignupRequest.java
back-end/src/main/java/com/feedhanjum/back_end/auth/controller/mapper/MemberMapper.java
back-end/src/main/java/com/feedhanjum/back_end/auth/exception/AuthControllerAdvice.java
back-end/src/main/java/com/feedhanjum/back_end/auth/service/AuthService.java
back-end/src/main/java/com/feedhanjum/back_end/core/exception/FindControllerAdvice.java
back-end/src/main/java/com/feedhanjum/back_end/core/exception/ValidationControllerAdvice.java
back-end/src/main/java/com/feedhanjum/back_end/member/controller/MemberController.java
back-end/src/main/java/com/feedhanjum/back_end/member/controller/dto/MemberDto.java
back-end/src/main/java/com/feedhanjum/back_end/member/domain/Member.java
back-end/src/main/java/com/feedhanjum/back_end/member/domain/ProfileImage.java
back-end/src/main/java/com/feedhanjum/back_end/member/service/MemberService.java
back-end/src/test/java/com/feedhanjum/back_end/auth/controller/AuthControllerTest.java
back-end/src/test/java/com/feedhanjum/back_end/auth/service/AuthServiceTest.java
back-end/src/test/java/com/feedhanjum/back_end/member/controller/MemberControllerTest.java
back-end/src/test/java/com/feedhanjum/back_end/member/service/MemberServiceTest.java

[FD-11] 회원 정보 조회 기능 구현

---

back-end/src/main/java/com/feedhanjum/back_end/auth/controller/AuthController.java
back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/LoginRequest.java
back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/LoginResponse.java
back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/MemberSignupRequest.java
back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/MemberSignupResponse.java
back-end/src/main/java/com/feedhanjum/back_end/auth/controller/mapper/MemberMapper.java
back-end/src/main/java/com/feedhanjum/back_end/auth/exception/AuthControllerAdvice.java
back-end/src/main/java/com/feedhanjum/back_end/auth/service/AuthService.java
back-end/src/main/java/com/feedhanjum/back_end/core/exception/FindControllerAdvice.java
back-end/src/main/java/com/feedhanjum/back_end/core/exception/ValidationControllerAdvice.java
back-end/src/main/java/com/feedhanjum/back_end/member/controller/MemberController.java
back-end/src/main/java/com/feedhanjum/back_end/member/controller/dto/MemberDto.java
back-end/src/main/java/com/feedhanjum/back_end/member/domain/Member.java
back-end/src/main/java/com/feedhanjum/back_end/member/domain/ProfileImage.java
back-end/src/main/java/com/feedhanjum/back_end/member/service/MemberService.java
back-end/src/test/java/com/feedhanjum/back_end/auth/controller/AuthControllerTest.java
back-end/src/test/java/com/feedhanjum/back_end/auth/service/AuthServiceTest.java
back-end/src/test/java/com/feedhanjum/back_end/member/controller/MemberControllerTest.java
back-end/src/test/java/com/feedhanjum/back_end/member/service/MemberServiceTest.java

FD-236
- get을 사용하는 도메인과, get 없이 즉시 접근 가능한 레코드로 편하게 구분 가능해짐 -> 가독성 향상!

[FD-236] 기존 DTO를 record로 통일

---

back-end/src/main/java/com/feedhanjum/back_end/member/controller/MemberController.java
back-end/src/test/java/com/feedhanjum/back_end/member/controller/MemberControllerTest.java
back-end/src/test/java/com/feedhanjum/back_end/member/service/MemberServiceTest.java

[FD-249] 프로필 이미지 수정

---

back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/RegularFeedbackRequestRepository.java
back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java

[FD-74] 정기 피드백 건너뛰기

---

back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Feedback.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Retrospect.java
back-end/src/main/java/com/feedhanjum/back_end/member/domain/Member.java
back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/Schedule.java
back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/ScheduleMember.java
back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
back-end/src/main/java/com/feedhanjum/back_end/team/domain/TeamMember.java

FD-254
- 불필요한 OneToMany 필드 삭제
- Member
- teamMembers
- scheduleMembers
- feedbacks
- retrospects
- Team
- teamMembers
- schedules

[FD-254] 불필요한 양방향 연관관계 제거

---

back-end/src/main/java/com/feedhanjum/back_end/core/config/QuerydslConfig.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Feedback.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepository.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackQueryService.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/service/dto/ReceivedFeedback.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/service/dto/ReceivedFeedbackDto.java
back-end/src/test/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepositoryTest.java
back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackQueryServiceTest.java

FD-33
- 피드백 조회용 서비스와 리포지터리 추가
- 피드백 조회용 리포지터리를 Querydsl로 구현
- 받은 피드백 조회 기능 구현

[FD-33] 받은 피드백 조회

---

back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepository.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackQueryService.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/service/dto/SentFeedbackDto.java
back-end/src/test/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepositoryTest.java
back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackQueryServiceTest.java

[FD-99] 보낸 피드백 조회

---

back-end/src/main/java/com/feedhanjum/back_end/team/controller/TeamController.java
back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerTest.java
back-end/src/test/java/com/feedhanjum/back_end/team/service/TeamServiceTest.java

[FD-22] 팀원 제거 구현

---

back-end/src/main/java/com/feedhanjum/back_end/core/constraints/ByteLength.java
back-end/src/main/java/com/feedhanjum/back_end/core/constraints/ByteLengthValidator.java
back-end/src/test/java/com/feedhanjum/back_end/core/constraints/ByteLengthValidatorTest.java

FD-232
- ascii code는 1byte, 그 외는 2byte로 판단하여 문자열 길이 제약을 할 수 있는 @ByteLength Valication Annotation 추가

[FD-232] byte 길이 validator 구현

---

front-end/package-lock.json
front-end/package.json
front-end/src/App.jsx
front-end/src/Layout.jsx
front-end/src/main.jsx

- react router 사용하여 라우팅
- 중첩라우팅을 위해 Layout 컴포넌트 제작 및 Outlet 컴포넌트 사용

[FD-261] feat: 레이아웃 및 라우팅 세팅

---

.github/workflows/ec2-deploy.yml
back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/FeedbackRefinementController.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/request/FeedbackRefineRequest.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/response/FeedbackRefineResponse.java
back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/response/RefineRemainCountResponse.java

FD-274
- AI 다듬기, 호출가능 횟수 조회 API 추가(기능 X)

[FD-274] ai 다듬기 api 컨트롤러 생성

---

front-end/package.json
front-end/src/App.jsx
front-end/src/components/Accordion.jsx
front-end/src/components/MainCard2.jsx
front-end/src/components/buttons/TextButton.jsx
front-end/src/pages/feedback/FeedbackRequest.jsx
front-end/src/pages/main/MainPage.jsx
front-end/src/pages/main/components/MainCard.jsx

- package.json의 script에 로컬 ip 관련 사항 추가
- 메인페이지 및 알람페이지 라우터 추가
- 아코디언 및 텍스트버튼 수정
- 피드백요청 페이지 쓸데없는 컴포넌트 제거
- 메인페이지 컴포넌트 배치

[FD-186] 메인 페이지 중간 pr

---

front-end/src/components/buttons/LargeButton.jsx
front-end/src/pages/auth/SignIn.jsx
front-end/src/pages/auth/SignUp.jsx
front-end/src/utility/inputChecker.js

계정 만들기 화면 일부 수정했습니다!
- 버튼 disabled 상태일때도 눌러서 현재 부족한 사항 확인 가능
- 로그인/회원가입 화면 로고 추가

[FD-181] 계정만들기 화면 개발

---

front-end/src/api/useFeedback.js
front-end/src/pages/calendar/components/ScheduleAction.jsx
front-end/src/pages/feedback/components/FeedBack.jsx
front-end/src/pages/teamspace/TeamSpaceEdit.jsx

[FD-214] 피드백 좋아요 기능 추가

---

back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/FrequentFeedbackRequestNotificationDto.java

FD-371
- 피드백 요청 알림 DTO에 요청자 id 추가

[FD-371] 피드백 요청 알림에 요청자 아이디 추가

---

front-end/src/App.jsx
front-end/src/api/useAuth.js
front-end/src/components/Certification.jsx
front-end/src/pages/auth/PasswordReset.jsx
front-end/src/pages/auth/SignIn.jsx
front-end/src/utility/inputChecker.js

[FD-374] 비밀번호 초기화 기능 구현

---

back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/RegularFeedbackRequestNotificationDto.java
back-end/src/main/java/com/feedhanjum/back_end/notification/domain/RegularFeedbackRequestNotification.java

FD-380
- 정기 피드백 요청 알림에 팀 이름 추가

[FD-380] 정기 피드백 요청 알림에 팀 이름 추가

---

README.md

docs: README.md 링크 수정

---

back-end/src/main/java/com/feedhanjum/back_end/core/exception/InternalErrorControllerAdvice.java

[FD-421]  non unique result exception lock timeout exception 503 핸들링
